version: '2'
services:
    aiopsgw-elasticsearch:
        image: elasticsearch:5.6.5
        # volumes:
        #     - ~/volumes/jhipster/aiopsgw/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9201:9201
            - 9301:9301
        command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
